# -*- coding: utf-8 -*-
"""Damos-lhe as boas-vindas ao Colab

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/notebooks/intro.ipynb
"""

# Criando uma tupla com as estacoes do ano
animais = ["cavalo", "ornintorrinco", "lagosta",]

# Exibindo a tupla completa
print(animais)

# Acessando elementos por indice (comeca em 0)
print(f"Primeiro animal: {animais[0]}")
print(f"Ultimo animal: {animais[-1]}")

animais.append("cachorro")
print(f"apos adiciona:{animais}")