# -*- coding: utf-8 -*-
"""Damos-lhe as boas-vindas ao Colab

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/notebooks/intro.ipynb
"""

# Criando uma lista de compras
frutas= ["banana, maçã , uva"]

# Exibindo a lista completa
print(f" frutas: {frutas}")

# Acessando o primeiro elemento (indice 0)
print(f"Primeira fruta: {frutas[0]}")

# acessando o ultimo elemento (indice -1)
print(f"ultima fruta: {len(frutas)}")

# Exercicio 1: Lista de compras
compras = ["Arroz", "Feijao", "Macarrao", "Leite", "Cafe"]
print(f"Lista inicial: {compras}")

# Exibindo a lista completa
print(f"compras:{compras}")

# Acessando o primeiro elemento (indice 0)
print(f" {compras[0]}")

# acessando o ultimo elemento (indice -1)
print(f" {compras [-1]}")