# -*- coding: utf-8 -*-
"""Damos-lhe as boas-vindas ao Colab

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/notebooks/intro.ipynb
"""

# Exercicio 1: Lista de compras
compras = ["Arroz", "Feijao", "Macarrao", "Leite", "Cafe"]
print(f"Lista inicial: {compras}")

# Exibindo a lista completa
print(f"compras:{compras}")

# Acessando o primeiro elemento (indice 0)
print(f" {compras[0]}")

# acessando o ultimo elemento (indice -1)
print(f" {compras [-1]}")

# Criando uma tupla com as estacoes do ano
estacoes = ("Primavera", "Verao", "Outono", "Inverno")

# Exibindo a tupla completa
print(estacoes)

# Acessando elementos por indice (comeca em 0)
print(f"Primeira estacao: {estacoes[0]}")
print(f"Ultima estacao: {estacoes[-1]}")