# -*- coding: utf-8 -*-
"""Damos-lhe as boas-vindas ao Colab

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/notebooks/intro.ipynb
"""

# Criando um dicionario com informacoes de uma pessoa
pessoa = {
    "nome": "Bernardo",
    "idade": 17,
    "cidade": "juiz de fora"
}

print(pessoa)